### ISSUE TITLE
License not obvious

### ISSUE THREAD

**Issue by BartMassey** [ProgrammingRust/examples#1]
I don't see any license information for this code anywhere. Maybe I'm just missing it?

**Comment by jimblandy** [comment]
Thanks for pointing this out. We'd agreed on a license for the code a month ago, but I forgot about it when I made the repo. Also added a license to the `mandelbrot` repo.

**Comment by jimblandy** [comment]
Fixed (for this repo) in 4b6001b2a87158d501abbcf784003013be4145e0

**Comment by jimblandy** [comment]
Fixed for fingertips: ProgrammingRust/fingertips@fecdce2521e2193bfaa91e10dcb41e17433c6aa5

**Comment by jimblandy** [comment]
Fixed for antisamples: ProgrammingRust/antisamples@5da6335ca2902f04ed9e1aa6f6be1f3ea9561cad

**Comment by jimblandy** [comment]
Fixed for mandelbrot in many changesets, merging the common-fixes branch into each of the implementation branches.

**Comment by BartMassey** [comment]
Thanks much!
