### ISSUE TITLE
Typo in page 317

### ISSUE THREAD

**Issue by koptan** [ProgrammingRust/examples#12]
I found a small typo in this code, page 317 :

```
impl<K,V> Hashmap<K,V> where K: Eq + Hash {
  fn get<Q: ?Sized>(&self,key: &Q) -> Option<&V>
  Where K:Borrow<Q>,
  Q: Eq+Hash
  {...}
}
```

The problem is in `Where K: Borrow<Q>` it should be `Where key: Borrow<Q>`
Instead of `K` it should be `key`.

**Comment by jimblandy** [comment]
Thanks for taking the time to report this. However, I think the code is correct: `where` clauses establish rules for generic type parameters, not values. So `K: Borrow<Q>` is placing a bound on the type parameter `K`, the hashmap's key type.

To verify this, you can check the book against the documentation for `HashMap::get`:
https://doc.rust-lang.org/stable/std/collections/hash_map/struct.HashMap.html#method.get

The book text is intended to match that.
